name: Build, Test, and Deploy

on:
  push:
    branches:
      - main

jobs:

  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '20'

      - name: Build with Maven
        run: mvn -B clean install -DskipTests

  Tests:
    runs-on: ubuntu-latest
    needs: [ Build ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '20'

      - name: Run Tests with Maven
        run: mvn test

  Deploy_to_DockerHub:
    runs-on: ubuntu-latest
    needs: [ Tests ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: ./.github/workflows/install_dependencies.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image and Push
        run: |-
          docker buildx create --use
          docker buildx build \
            --file ./dockerfile \
            --tag ${{ secrets.REPOSITORY_NAME }}/${{ secrets.DOCKER_CONTAINER_NAME }}:${{ secrets.DOCKER_CONTAINER_TAG }} \
            --push .
